#### create a new ordering, 1. create stripe session

POST http://localhost:4310/api/orders
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkFWZmxpUGNDb3Z0SUt0QVF1LXlVYyJ9.eyJpc3MiOiJodHRwczovL2Rldi0zbTN2Z2RpdS51cy5hdXRoMC5jb20vIiwic3ViIjoiOUx4dEVCWWc5MU84Q2c3QU5IQkI5b1pUN2ZxQlREeDBAY2xpZW50cyIsImF1ZCI6Imh0dHAvL2FwaS1wYXJpc2NhZmUiLCJpYXQiOjE2NjUzMTY0OTUsImV4cCI6MTY2NTQwMjg5NSwiYXpwIjoiOUx4dEVCWWc5MU84Q2c3QU5IQkI5b1pUN2ZxQlREeDAiLCJzY29wZSI6ImFkbWluOioiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJwZXJtaXNzaW9ucyI6WyJhZG1pbjoqIl19.kRPf7EYrfENrA7OscTWELFUzWaIjss1Hqll5u4Zmhj84HxrRoTFkLFcCMdGX5bQ7vWFjgHVGYec8uEIF3AGtdOf4EQlZyIWkB1ZmYQain8gaR6OdXzsAbTLc18ML48E8gYhQ6UR0J7GnmYkTYNPzX2LL2ee8NKAL8LjAGSt9RfOJ-qDwN-zWaAWxl7jz30vwNMlqQwbQbVj7cSLluVHiXGCJdN7WOeeR0jfoi1sAGXktePknAOdmFKyoZkMpBB0ttedr4ZwKTuRDb6I89-Qbiipq8pCjgjLnC6KSjbPQ6SmQJ10ny0vTq0NeRIzKTzoTTRkfDg94wymny_JIpPYB7w

{
  "order_data": {
    "dishes" : [
      {
      "_id": "123",
      "name": "idli",
      "description": "served with chutney and sambar",
      "count" : "1",
      "price": "250"
      }
    ], 
    "address" :{
      "full_name" : "Sam",
      "line1" : "1st Ave",
      "line2" : "",
      "city" : "San Sebastian",
      "zip" : "66033",
      "state" : "CA",
      "country" : "usa",
      "phone" : "918217699518"
    }, 
    "order_total" : "120"

  }
}


### update order status
PUT http://localhost:4310/api/orders/cs_test_a1fLx9I3Llqw5YIE2kFGAz4iH85pxSlC0mqpDTBiwiGTbnfbSFphXvhJ2e
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkFWZmxpUGNDb3Z0SUt0QVF1LXlVYyJ9.eyJpc3MiOiJodHRwczovL2Rldi0zbTN2Z2RpdS51cy5hdXRoMC5jb20vIiwic3ViIjoiOUx4dEVCWWc5MU84Q2c3QU5IQkI5b1pUN2ZxQlREeDBAY2xpZW50cyIsImF1ZCI6Imh0dHAvL2FwaS1wYXJpc2NhZmUiLCJpYXQiOjE2NjUwMDA4NzQsImV4cCI6MTY2NTA4NzI3NCwiYXpwIjoiOUx4dEVCWWc5MU84Q2c3QU5IQkI5b1pUN2ZxQlREeDAiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.GyoFVoVNo597GhdxOVqiI0UbD0W3Q8V5kuEaZOYbz_Mu1XZjbOcacRbwoOYGVaoH1Mcyx7a2jjiDuaWzlB1snshdKbMIO89MpLCxnCajMiK7uRKWoBlfb7ARaval-NP5qxDleuulYTR7QYE40wTVQaUWp0xnGPKXHmRUENP50AYvp5oYeKiIz4QYQ8f7ljCITofur2Oh_JGVYjtArqTswug7pZcNRUc6S8Diipt5v03sMxKKL4w1WLnySbKuPh9mn31pQTAcz1kVaYtbAAfLOwGwSpTcCUwVsWTI_PLF6O4G0nz1CNKEMdyf0atZG8CByDFexLzO569DkkC6yWQfMA


### get orders for a given user
GET http://localhost:4310/api/orders
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkFWZmxpUGNDb3Z0SUt0QVF1LXlVYyJ9.eyJpc3MiOiJodHRwczovL2Rldi0zbTN2Z2RpdS51cy5hdXRoMC5jb20vIiwic3ViIjoiOUx4dEVCWWc5MU84Q2c3QU5IQkI5b1pUN2ZxQlREeDBAY2xpZW50cyIsImF1ZCI6Imh0dHAvL2FwaS1wYXJpc2NhZmUiLCJpYXQiOjE2NjUyNTM1NDAsImV4cCI6MTY2NTMzOTk0MCwiYXpwIjoiOUx4dEVCWWc5MU84Q2c3QU5IQkI5b1pUN2ZxQlREeDAiLCJzY29wZSI6ImFkbWluOioiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJwZXJtaXNzaW9ucyI6WyJhZG1pbjoqIl19.guF4qDDQgqtUMKV7ITNmVdkE-iF0K2KDG_z1JunhgFERJEney3zZf71JTnyYiXPouKlKctZmWiXEtrBWZXmV5C_QTLI7joOeKiCAXdODfu3JNRP_lpyLmWQv3JpvVrmQ8F_VcXJU2bNDZf8lgBNBfju9YBilwTYKw3B5oavbay32uD_Z7ll7qKoujlyCM_1P71RjqGA49mDKksxm-3Ekdl38Os1-YMUY_9rdHyW1VN_GeBwVbKOPBPd8sOXYEaIKgJ7FgcGd68u08QDjVKJFHJpgMBRtLJawN2G9xj9wr56MuIZfQ2Cq8hgyqsyxRPa2hT_lpWADchuQha5LXMkQPQ


###get orders for admin
GET http://localhost:4310/api/orders/admin
Accept: application/json 
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkFWZmxpUGNDb3Z0SUt0QVF1LXlVYyJ9.eyJpc3MiOiJodHRwczovL2Rldi0zbTN2Z2RpdS51cy5hdXRoMC5jb20vIiwic3ViIjoiOUx4dEVCWWc5MU84Q2c3QU5IQkI5b1pUN2ZxQlREeDBAY2xpZW50cyIsImF1ZCI6Imh0dHAvL2FwaS1wYXJpc2NhZmUiLCJpYXQiOjE2NjUyMzAwMjYsImV4cCI6MTY2NTMxNjQyNiwiYXpwIjoiOUx4dEVCWWc5MU84Q2c3QU5IQkI5b1pUN2ZxQlREeDAiLCJzY29wZSI6ImFkbWluOioiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJwZXJtaXNzaW9ucyI6WyJhZG1pbjoqIl19.HqWUcuLGxQyHL_nfqZbRMk7kiggzXmCQci3DqcfUwhAFYAbzkWcLfhW2b9GAucTVEBDpvYF5kPqgg8QH66O3w7D7GNRVsWXAHwUCVkLaV5UQhnDexgqOdbiwlYXbYhi5hic2bLzJTP8aa_WyRITMgE7MEZL8viuYzGldcKNto_SHxnXHMs4lc61IOermyNs-jsFmat_t0Z5409DxriyLC-PREFGg4qaIuDryIwyCRoZA0GzfDVy4BfPMQjasU43fhfoIkvKqbblkCV2Db4ag4N9z6XbR5P2T8z_3aCsRwKC5bHMRLMoKxercp_M6ZEwF7GQrtcpiZyULvyQttHOxdQ

### update order status
PUT http://localhost:4310/api/orders/79d7b0f4-c634-488f-96f7-f513d5f9bb91
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkFWZmxpUGNDb3Z0SUt0QVF1LXlVYyJ9.eyJpc3MiOiJodHRwczovL2Rldi0zbTN2Z2RpdS51cy5hdXRoMC5jb20vIiwic3ViIjoiOUx4dEVCWWc5MU84Q2c3QU5IQkI5b1pUN2ZxQlREeDBAY2xpZW50cyIsImF1ZCI6Imh0dHAvL2FwaS1wYXJpc2NhZmUiLCJpYXQiOjE2NjUyNTM1NDAsImV4cCI6MTY2NTMzOTk0MCwiYXpwIjoiOUx4dEVCWWc5MU84Q2c3QU5IQkI5b1pUN2ZxQlREeDAiLCJzY29wZSI6ImFkbWluOioiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJwZXJtaXNzaW9ucyI6WyJhZG1pbjoqIl19.guF4qDDQgqtUMKV7ITNmVdkE-iF0K2KDG_z1JunhgFERJEney3zZf71JTnyYiXPouKlKctZmWiXEtrBWZXmV5C_QTLI7joOeKiCAXdODfu3JNRP_lpyLmWQv3JpvVrmQ8F_VcXJU2bNDZf8lgBNBfju9YBilwTYKw3B5oavbay32uD_Z7ll7qKoujlyCM_1P71RjqGA49mDKksxm-3Ekdl38Os1-YMUY_9rdHyW1VN_GeBwVbKOPBPd8sOXYEaIKgJ7FgcGd68u08QDjVKJFHJpgMBRtLJawN2G9xj9wr56MuIZfQ2Cq8hgyqsyxRPa2hT_lpWADchuQha5LXMkQPQ

{
  "new_status": "Abandoned"
}




### cancel order
DELETE http://localhost:4310/api/orders/2f252ab2-7994-418d-bb02-a3504edcc666
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkFWZmxpUGNDb3Z0SUt0QVF1LXlVYyJ9.eyJpc3MiOiJodHRwczovL2Rldi0zbTN2Z2RpdS51cy5hdXRoMC5jb20vIiwic3ViIjoiOUx4dEVCWWc5MU84Q2c3QU5IQkI5b1pUN2ZxQlREeDBAY2xpZW50cyIsImF1ZCI6Imh0dHAvL2FwaS1wYXJpc2NhZmUiLCJpYXQiOjE2NjUzMjE2ODAsImV4cCI6MTY2NTQwODA4MCwiYXpwIjoiOUx4dEVCWWc5MU84Q2c3QU5IQkI5b1pUN2ZxQlREeDAiLCJzY29wZSI6ImFkbWluOioiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJwZXJtaXNzaW9ucyI6WyJhZG1pbjoqIl19.lGMG1AvOXfn9M9jxUyZQ46TYC_OYNiTTRXz8pWUPNEAyXAMpz5jvR8Z8nP7S5kWftH5RQ4wIVFPenJEWIR-UqowIGDCzXSgCTVf8TaU1EVqGOGmosEI-zF21448a-b0wWX4mcPp4yuFg8mMsPDj62NOFps_XeUT3zPGagOCRUVerS7o-wEl-_dZCQnkL1LHMLeh8I3dOKqg0NEzIazcqr9A314v88Cj6rdSw7JdPTYVEae-wQRHXMaf7Svu5ftMDOpd-yal7rqaPO1BVlSEokz8sO-RznqeS8qyP43vHzsBqqblmN7ZQ0SDzxcQm5q-MLM8B0JF6Ja3ghMQO1_5irQ

{
  "new_status": "Canceled"
}

















