### create user
POST http://localhost:4310/api/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkFWZmxpUGNDb3Z0SUt0QVF1LXlVYyJ9.eyJpc3MiOiJodHRwczovL2Rldi0zbTN2Z2RpdS51cy5hdXRoMC5jb20vIiwic3ViIjoiOUx4dEVCWWc5MU84Q2c3QU5IQkI5b1pUN2ZxQlREeDBAY2xpZW50cyIsImF1ZCI6Imh0dHAvL2FwaS1wYXJpc2NhZmUiLCJpYXQiOjE2NjQ3ODQzNjksImV4cCI6MTY2NDg3MDc2OSwiYXpwIjoiOUx4dEVCWWc5MU84Q2c3QU5IQkI5b1pUN2ZxQlREeDAiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.AaRsR8AKVQM8FluhSCpyNgD9rwJqhrdjFm3YROaSLcKkmjvl7j32eSOGHw2TpqDn8Bq3e2GK5DKTlfgV7Jah4ovyPJ9b1F6Cx3tpPV_F7Rnl4ABM7RrxlVG7Y9kVOv2jybVfhEVnr2vXHOYkqRO5iqPLqJtOwpe5cJybkadMevQCTb__EMsY1rRBz2br3SP1nQPJ8b6W9hllpFY_dDNL4sRc4GdDryrCgafFGftgsxNuEUhfkqqfSp9ifF-rG9PQMKfn_tNV040v1QyrRFVvuHZfyEKyogzsZsxTwB2R0CcbKKbKwXW_WbL6PJ0zyciARH4clSx-Fstq7Mk1t2fSpw

{
  "_id": "123457645333445678",
  "email" : "Test10312455678@example.com"
}

### get user by id
GET http://localhost:4317/api/users/1234576
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkFWZmxpUGNDb3Z0SUt0QVF1LXlVYyJ9.eyJpc3MiOiJodHRwczovL2Rldi0zbTN2Z2RpdS51cy5hdXRoMC5jb20vIiwic3ViIjoiOUx4dEVCWWc5MU84Q2c3QU5IQkI5b1pUN2ZxQlREeDBAY2xpZW50cyIsImF1ZCI6Imh0dHAvL2FwaS1wYXJpc2NhZmUiLCJpYXQiOjE2NjQyMTYxODEsImV4cCI6MTY2NDMwMjU4MSwiYXpwIjoiOUx4dEVCWWc5MU84Q2c3QU5IQkI5b1pUN2ZxQlREeDAiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.ckfsxO_uYP8bIZQ7ZAHozvaLAHnPnCDDu5Ih57kzy_FrOxuzLZk3NoHhD2UEajQ3-xykbTBkKtvh2kp1gs_9LhKMIRSHY4WulKYWOeC687U-S-N2VpdYwxFOZ7MUjyfFB14NdbVVzdClmF_ExRpdEGXfAwC2N8pCqUeC1UNysu7ngraNxy36YlDI6dUMbIvmVhyW4WEruc5s1mnSscYjCKxOGb1nX8qyC_DNwGi7Q-ZLKb8q9S_9ooBsCsKFRpjwpHVXAAtWGUFpdZ3ElFDNetyKu8Az-n_dEq-gx0WZznuKa-7vBt3dPs0yk_oh9YtEIhcHPPpjZsaKWPYF54PI6A


### update address
PUT http://localhost:4317/api/users/60e37601962cd9007051e76f/address
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkFWZmxpUGNDb3Z0SUt0QVF1LXlVYyJ9.eyJpc3MiOiJodHRwczovL2Rldi0zbTN2Z2RpdS51cy5hdXRoMC5jb20vIiwic3ViIjoiOUx4dEVCWWc5MU84Q2c3QU5IQkI5b1pUN2ZxQlREeDBAY2xpZW50cyIsImF1ZCI6Imh0dHAvL2FwaS1wYXJpc2NhZmUiLCJpYXQiOjE2NjQyMTYxODEsImV4cCI6MTY2NDMwMjU4MSwiYXpwIjoiOUx4dEVCWWc5MU84Q2c3QU5IQkI5b1pUN2ZxQlREeDAiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.ckfsxO_uYP8bIZQ7ZAHozvaLAHnPnCDDu5Ih57kzy_FrOxuzLZk3NoHhD2UEajQ3-xykbTBkKtvh2kp1gs_9LhKMIRSHY4WulKYWOeC687U-S-N2VpdYwxFOZ7MUjyfFB14NdbVVzdClmF_ExRpdEGXfAwC2N8pCqUeC1UNysu7ngraNxy36YlDI6dUMbIvmVhyW4WEruc5s1mnSscYjCKxOGb1nX8qyC_DNwGi7Q-ZLKb8q9S_9ooBsCsKFRpjwpHVXAAtWGUFpdZ3ElFDNetyKu8Az-n_dEq-gx0WZznuKa-7vBt3dPs0yk_oh9YtEIhcHPPpjZsaKWPYF54PI6A

{
  "full_name" : "Jane Smith",
  "line1" : "1st Ave",
  "line2" : "",
  "city" : "BLR",
  "state" : "KA",
  "zip": "560002",
  "country" : "IND",
  "phone" : "918041612899"
}

### get address for user
GET http://localhost:4317/api/users/101694842557448818682/address
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkFWZmxpUGNDb3Z0SUt0QVF1LXlVYyJ9.eyJpc3MiOiJodHRwczovL2Rldi0zbTN2Z2RpdS51cy5hdXRoMC5jb20vIiwic3ViIjoiOUx4dEVCWWc5MU84Q2c3QU5IQkI5b1pUN2ZxQlREeDBAY2xpZW50cyIsImF1ZCI6Imh0dHAvL2FwaS1wYXJpc2NhZmUiLCJpYXQiOjE2NjQyMTYxODEsImV4cCI6MTY2NDMwMjU4MSwiYXpwIjoiOUx4dEVCWWc5MU84Q2c3QU5IQkI5b1pUN2ZxQlREeDAiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.ckfsxO_uYP8bIZQ7ZAHozvaLAHnPnCDDu5Ih57kzy_FrOxuzLZk3NoHhD2UEajQ3-xykbTBkKtvh2kp1gs_9LhKMIRSHY4WulKYWOeC687U-S-N2VpdYwxFOZ7MUjyfFB14NdbVVzdClmF_ExRpdEGXfAwC2N8pCqUeC1UNysu7ngraNxy36YlDI6dUMbIvmVhyW4WEruc5s1mnSscYjCKxOGb1nX8qyC_DNwGi7Q-ZLKb8q9S_9ooBsCsKFRpjwpHVXAAtWGUFpdZ3ElFDNetyKu8Az-n_dEq-gx0WZznuKa-7vBt3dPs0yk_oh9YtEIhcHPPpjZsaKWPYF54PI6A

























