### create user
POST http://localhost:4310/api/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkFWZmxpUGNDb3Z0SUt0QVF1LXlVYyJ9.eyJpc3MiOiJodHRwczovL2Rldi0zbTN2Z2RpdS51cy5hdXRoMC5jb20vIiwic3ViIjoiOUx4dEVCWWc5MU84Q2c3QU5IQkI5b1pUN2ZxQlREeDBAY2xpZW50cyIsImF1ZCI6Imh0dHAvL2FwaS1wYXJpc2NhZmUiLCJpYXQiOjE2NjQ4NzMyODksImV4cCI6MTY2NDk1OTY4OSwiYXpwIjoiOUx4dEVCWWc5MU84Q2c3QU5IQkI5b1pUN2ZxQlREeDAiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.OKLLx3tOXHYH-IlLHZjfCT5N04riwd2BxGGcNx7IklES2dD-xwmd1CMY83RIqQacKkkOebULgfnnfQXfRPXEacQzKr9tijZ5t5J9gUVG5NgqQFR0LMmOpQkYcOg9v5a_knX5qRf63VWoxnRM_mbEdHZbJev7rOMHnJ9qxvcsgvpFfN2EomOf_Gyi5eyRL4VxIgdF4_cqR3eEVGp1X_7sIESbySVO74tJ6-bx1G2R0qkVVphszd5ms_jTI4-HelXjtWZVxHB1VSjBZfl5PU_52dgpescK7zD1zovqdlcDawaJsm_G8c440HnEHfjj9FEujt83SyaIFXL9TiMHU9aQlw

{
  "_id": "1234576453334456783",
  "email" : "Test103124556738@example.com"
}

### get user by id
GET http://localhost:4310/api/users/1234576
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkFWZmxpUGNDb3Z0SUt0QVF1LXlVYyJ9.eyJpc3MiOiJodHRwczovL2Rldi0zbTN2Z2RpdS51cy5hdXRoMC5jb20vIiwic3ViIjoiOUx4dEVCWWc5MU84Q2c3QU5IQkI5b1pUN2ZxQlREeDBAY2xpZW50cyIsImF1ZCI6Imh0dHAvL2FwaS1wYXJpc2NhZmUiLCJpYXQiOjE2NjQ3ODQzNjksImV4cCI6MTY2NDg3MDc2OSwiYXpwIjoiOUx4dEVCWWc5MU84Q2c3QU5IQkI5b1pUN2ZxQlREeDAiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.AaRsR8AKVQM8FluhSCpyNgD9rwJqhrdjFm3YROaSLcKkmjvl7j32eSOGHw2TpqDn8Bq3e2GK5DKTlfgV7Jah4ovyPJ9b1F6Cx3tpPV_F7Rnl4ABM7RrxlVG7Y9kVOv2jybVfhEVnr2vXHOYkqRO5iqPLqJtOwpe5cJybkadMevQCTb__EMsY1rRBz2br3SP1nQPJ8b6W9hllpFY_dDNL4sRc4GdDryrCgafFGftgsxNuEUhfkqqfSp9ifF-rG9PQMKfn_tNV040v1QyrRFVvuHZfyEKyogzsZsxTwB2R0CcbKKbKwXW_WbL6PJ0zyciARH4clSx-Fstq7Mk1t2fSpw


### update address
PUT http://localhost:4310/api/users/103862780491452796970/address
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkFWZmxpUGNDb3Z0SUt0QVF1LXlVYyJ9.eyJpc3MiOiJodHRwczovL2Rldi0zbTN2Z2RpdS51cy5hdXRoMC5jb20vIiwic3ViIjoiOUx4dEVCWWc5MU84Q2c3QU5IQkI5b1pUN2ZxQlREeDBAY2xpZW50cyIsImF1ZCI6Imh0dHAvL2FwaS1wYXJpc2NhZmUiLCJpYXQiOjE2NjQ3ODQzNjksImV4cCI6MTY2NDg3MDc2OSwiYXpwIjoiOUx4dEVCWWc5MU84Q2c3QU5IQkI5b1pUN2ZxQlREeDAiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.AaRsR8AKVQM8FluhSCpyNgD9rwJqhrdjFm3YROaSLcKkmjvl7j32eSOGHw2TpqDn8Bq3e2GK5DKTlfgV7Jah4ovyPJ9b1F6Cx3tpPV_F7Rnl4ABM7RrxlVG7Y9kVOv2jybVfhEVnr2vXHOYkqRO5iqPLqJtOwpe5cJybkadMevQCTb__EMsY1rRBz2br3SP1nQPJ8b6W9hllpFY_dDNL4sRc4GdDryrCgafFGftgsxNuEUhfkqqfSp9ifF-rG9PQMKfn_tNV040v1QyrRFVvuHZfyEKyogzsZsxTwB2R0CcbKKbKwXW_WbL6PJ0zyciARH4clSx-Fstq7Mk1t2fSpw

{
  "full_name" : "Jane Wilson",
  "line1" : "1st Ave",
  "line2" : "",
  "city" : "BLR",
  "state" : "KA",
  "zip": "560002",
  "country" : "IND",
  "phone" : "918041612899"
}

### get address for user
GET http://localhost:4310/api/users/103862780491452796970/address
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkFWZmxpUGNDb3Z0SUt0QVF1LXlVYyJ9.eyJpc3MiOiJodHRwczovL2Rldi0zbTN2Z2RpdS51cy5hdXRoMC5jb20vIiwic3ViIjoiOUx4dEVCWWc5MU84Q2c3QU5IQkI5b1pUN2ZxQlREeDBAY2xpZW50cyIsImF1ZCI6Imh0dHAvL2FwaS1wYXJpc2NhZmUiLCJpYXQiOjE2NjQ3ODQzNjksImV4cCI6MTY2NDg3MDc2OSwiYXpwIjoiOUx4dEVCWWc5MU84Q2c3QU5IQkI5b1pUN2ZxQlREeDAiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.AaRsR8AKVQM8FluhSCpyNgD9rwJqhrdjFm3YROaSLcKkmjvl7j32eSOGHw2TpqDn8Bq3e2GK5DKTlfgV7Jah4ovyPJ9b1F6Cx3tpPV_F7Rnl4ABM7RrxlVG7Y9kVOv2jybVfhEVnr2vXHOYkqRO5iqPLqJtOwpe5cJybkadMevQCTb__EMsY1rRBz2br3SP1nQPJ8b6W9hllpFY_dDNL4sRc4GdDryrCgafFGftgsxNuEUhfkqqfSp9ifF-rG9PQMKfn_tNV040v1QyrRFVvuHZfyEKyogzsZsxTwB2R0CcbKKbKwXW_WbL6PJ0zyciARH4clSx-Fstq7Mk1t2fSpw

























