### get all categories
GET http://localhost:4317/api/categories
Accept: application/json

### get invalid route
GET http://localhost:4317/api/categories2
Accept: application/json

### Create a new category
POST  http://localhost:4317/api/categories
Content-Type: application/json
Accept: application/json

{
  "name": "Mexico"
}

### get category by id
GET http://localhost:4317/api/categories/63340da816d64904482a6566
Accept: application/json